HRM configuration and tests.
Kodjevlar/snabb pull request #9
Opened 2016-10-13 13:09 UTC by JoelRoxell

### Description

- Implements HMR configuration used under development.
- Implemented tests which run via jsdom in the terminal.
- Added pre-push hook.
- Added code coverage.

2016-10-13 13:20 UTC, LinusLjung requested changes

2016-10-13 13:20 UTC, LinusLjung commented on .gitignore
> +<<<<<<< Updated upstream
Unresolved merge conflict

2016-10-13 13:20 UTC, LinusLjung commented on pre-push.sh
> +git stash -q --keep-index
I'd suggest adding the `-u` flag to also stash untracked files

2016-10-13 13:20 UTC, LinusLjung commented on pre-push.sh
> +git stash pop -q
You need to check if anything was actually stashed before popping. Otherwise unwanted code could be popped instead

2016-10-13 16:04 UTC, JoelRoxell commented on pre-push.sh
> +git stash pop -q
Removed the hook implementation. We'll use travic to test builds which will defeat the purpose of pre-tests.

2016-10-14 06:27 UTC, LinusLjung approved these changes

2016-10-14 06:43 UTC, merged